 controller_frecuency: 3.0
 TrajectoryPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 2.0
  acc_lim_theta: 2.0
  max_vel_x: 0.8
  min_vel_x: 0.1
  max_vel_theta: 2.0
  min_vel_theta: 0.3
  min_in_place_vel_theta: 0.4
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.3
  escape_vel: -0.20
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 2.0
  holonomic_robot: false

#Goal Tolerance Parameters
  yaw_goal_tolerance: 0.8
  xy_goal_tolerance: 0.8

#Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 5
  vy_samples: 1
  vtheta_samples: 10
  

#Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 1.80
  gdist_scale: 0.80
  occdist_scale: 0.06
  heading_lookahead: 1.0
  heading_scoring: false
  heading_scoring_timestep: 0.5
  dwa: true

  publish_cost_grid_pc: true

#Oscillation Prevention Parameters
 oscillation_reset_dist: 0.01

#Global Plan Parameters
 simple_attractor: true
 recovery_behavior_enable: true
 clearing_rotation_allowed: true

 path_distance_bias: 0.6
 goal_distance_bias: 0.6
